from telegram.ext import ConversationHandler

from database import Database
# State definitions for conversation
(SELECT_ACTION, GENIUS, TELEGRAPH, CHECK_GENIUS_ALBUM, CUSTOMIZE_GENIUS, TYPING,
 OPTION1, OPTION2, OPTION3, OPTION4, IDENTIFIER, AUTHOR_NAME, AUTHOR_URL, ANNOTATIONS,
 LYRICS_LANG, START_OVER, INCLUDE, TYPING_ALBUM, STATISTICS, CURRENT_LEVEL,
 CREATE_ACCOUNT, CREATE_PAGES, CUSTOMIZE_TELEGRAPH, LOGIN, DESCRIPTION, SELF,
 CHECK_GENIUS_SONG, TYPING_SONG, TYPING_ACCOUNT, DOWNLOAD_ALBUM) = range(30)

END = ConversationHandler.END

username = ''

database = Database(table='data')
