name: Upload report

on:
  push:
    branches: [master]


env:
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64

jobs:
  upload_coverage:
    runs-on: ubuntu-18.04

    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    needs: build-and-test

    steps:
      - name: Set ENV for codeclimate
        run: |
          echo "{GIT_BRANCH}={$GITHUB_REF}" >> $GITHUB_ENV
          echo "{GIT_COMMIT_SHA}={$GITHUB_SHA}" >> $GITHUB_ENV

      - name: Download test coverage reporter
        run: curl -L $CC_TEST_REPORTER_URL > cc-test-reporter

      - name: Give test coverage reporter executable permissions
        run: chmod +x cc-test-reporter

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report

      - name: Aggregate & upload results to Code Climate
        run: |
          ./cc-test-reporter upload-coverage -i coverage.json
